# Generated by Django 5.1.6 on 2025-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_productcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/products/'),
        ),
    ]
